---
name: Sample
description: "Rule which trigger a workflow based of email subject"
pack: azure_vm
enabled: true
trigger:
  type: azure_vm.smtp.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: VM Create
    type: contains
action:
  ref: azure_vm.send_email
    account: sendmail
    email_from: stackstorm.alert@gmail.com
    email_to: harsh6100@gmall.com
    message: 'hi there senson working properly'
    subject: 'VM created'
