---
name: Sample
description: "Rule which trigger a workflow based of email subject"
pack: azure_vm
enabled: true
trigger:
  type: azure_vm.imap.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: VM Create
    type: contains
action:
  ref: core.local
  parameters:
    cmd: "echo {{trigger.subject}}"
